config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#index'

  resources :to_dos do
    member do
      post 'toggle'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do.rb
class ToDo < ApplicationRecord
    belongs_to :user
    validates :description, length: {minimum: 5, maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :to_dos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource) 
    # This makes it so the user is redirected to the to_dos_path instead
    # of to the root path
    stored_location_for(resource) || to_dos_path 
  end

  def is_number? (string)
    return true if Float(string) rescue false
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to to_dos_path
    end
  end
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController
  before_action :authenticate_user!
  before_action :find_to_do, only: [:destroy, :edit, :update, :toggle]

  def index
    @total_record_num = current_user.to_dos.count
    task_show = params[:task_show]
    if task_show.nil?
      redirect_to to_dos_path(task_show: 20)
    else
      if task_show == "all"
        @task_show_num = @total_record_num
      elsif is_number?(task_show) && task_show.to_i >= 0 
        @task_show_num = task_show.to_i 
        if @task_show_num > @total_record_num
          redirect_to to_dos_path(task_show: "all")
        end
      else 
        redirect_to to_dos_path(task_show: 20)
      end
    end

    @todos = current_user.to_dos.order("updated_at DESC").limit(@task_show_num)
  end

  def create
    @todo = current_user.to_dos.build(todo_params)
    @todo.completed = false

    if (!@todo.save)
      flash[:alert] = @todo.errors.full_messages[0]
    end
    redirect_to to_dos_path
  end

  def destroy
    @todo.destroy
    redirect_to to_dos_path
  end

  def edit
  end

  def update
    if (@todo.update(todo_params))
      flash[:notice] = "Task updated successfully!"
      redirect_to to_dos_path
    else
      render 'edit'
    end
  end

  def toggle
    @todo.completed = !@todo.completed 
    @todo.save
    redirect_to to_dos_path
  end

  private

  def find_to_do
    @todo = ToDo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:description, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/to_dos_helper.rb
module ToDosHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <span class="text-muted">Ky Kartchner &copy; 2020</span>
</footer>

app/views/layouts/_messages.html.erb
<% if alert %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

<% if notice %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <%= link_to 'RailsToDo', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item active">
        <% if user_signed_in? %>
        <%= link_to current_user.email, '#', class: "nav-link" %>
        <% else %>
        <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        <% end %>
      </li>
      <li class="nav-item active">
        <% if user_signed_in? %>
        <%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete %>
        <% else %>
        <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>RailsToDo</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="main">
    <%= render 'layouts/navigation' %>
    <div class="jumbotron jumbotron-fluid">
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>

</html>

app/views/pages/index.html.erb
<h1 class="display-4">Welcome to RailsToDo</h1>
<%= render 'layouts/messages' %>
<p class="lead">A basic to do list for all people who have things to do!</p>
<p class="lead"><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg", role: "button" %>
<%= link_to "Login", user_session_path, class: "btn btn-primary btn-lg", role: "button" %> </p>

app/views/to_dos/_new.html.erb
<%= form_with scope: :todo, url: to_dos_path, local: true do |f| %>
    <%= f.text_field :description, {class: 'form-control', id: 'newToDo', placeholder: 'What do you need to do? (Type here then press Enter)'} %>
<% end %>

app/views/to_dos/_todos.html.erb
<% @todos.each do |todo| %>
<li class="list-group-item">
  <span>
    <input type="checkbox" data-remote="true" data-url="/to_dos/<%=todo.id %>/toggle" data-method="POST" <%= todo.completed ? 'checked' : ''%> />

    <% if todo.completed %><%# Strikethrough description if it is marked as completed. %>
    <del><%= todo.description %></del>
    <% else %><%# Else show description normally %>
    <%= todo.description %>
    <% end %>

  </span>
  <span class="todoActions">
    <%= link_to '[E]', edit_to_do_path(todo) %>
    <%= link_to '[X]', todo,
                method: :delete,
                data: {confirm: 'Are you sure you want to delete?'} %>
    <span>
</li>
<% end %>

app/views/to_dos/edit.html.erb
<div class="container">
  <h1 class="display-4">Edit Task</h1>
  <ul class="list-group">
    <%= form_with scope: :todo, url: to_do_path(@todo), method: :patch, local: true do |f| %>
    <%= f.text_field :description, {:class => 'form-control', :placeholder => 'What do you need to do? (Type here then press Enter)'} %>
    <% end %>
  </ul>
  <%= link_to '[Cancel and go back to todo list]', to_dos_path, class: "text-info" %>
</div>

app/views/to_dos/index.html.erb
<%= javascript_pack_tag 'todo_scripts' %>
<div class="container" style="margin-bottom: -55px">
  <h1 class="display-4">My Tasks</h1>
  <%= render 'layouts/messages' %>
  <ul class="list-group" id="todoList">
    <%= render 'to_dos/new'%>
    <span id="recordShowNum" class="lead">Showing
      <%= @task_show_num.to_s + " of " %><span id="totalRecordSpan"><%= @total_record_num.to_s %></span>
      <%= (@task_show_num < @total_record_num ? " (scroll down to load more)" : "") %>
    </span>
    <div id="todos-div" class="overflow-auto" style="max-height: 360px">
      <%= render 'to_dos/todos'%>
    </div>

    <%
=begin%>
 <button onclick="">Load more</button> 
<%
=end%>
  </ul>
</div>

app/views/users/new.html.erb
<h1 class="display-4">Create an Account</h1>
<%= form_with(model: @user, class: "form-signin", local: true) do |f| %>
  <div>
  <%= f.label :name, class: "sr-only" %>
  <%= f.text_field :name, class: "form-control", placeholder: "Name" %>

  <%= f.label :email, class: "sr-only" %>
  <%= f.email_field :email, class: "form-control", placeholder: "Email address" %>

  <%
=begin%>
 <%= f.label :password, class: "sr-only" %>
  <%= f.password_field :password, class: "form-control", placeholder: "Password" %> 
<%
=end%>
  </div>

  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
<% end %>